### ISSUE TITLE
Problem on Device "Samsung Galaxy Note 5"

### ISSUE THREAD

**Issue by phanosh** [luethi/Discharge_Optical_Measurement#14]
When trying to create an account, the user got a notification saying "we cannot create an account, please try again later"

Also, when the user clicked "Forgot password" he received an email with a link to reset the password. The link however seems to be wrong as it simply gets you to the sign in page of discharge.ch. (This is when accessing the link on the mobile phone, not on a normal machine)

**Comment by luethi** [comment]
I have just passed the ticket on to ranko

**Comment by rmunk** [comment]
Can you give us the username he was trying to use and the date/time this happened so @gskoljarev can check out the server logs.
As for the reset password link, I think @mihaellenic is the one that should check it out. Or maybe it is also @gskoljarev. So I'm passing the ball to them...

**Comment by phanosh** [comment]
The username was Bamba1 and it was today (28/09) around 10:30am zurich time

**Comment by mihaellenic** [comment]
@gskoljarev will have to check on the backend for this issue. The frontend seems to be working fine...
@phanosh could you maybe get us the email that user received?

**Comment by phanosh** [comment]
@mihaellenic bambabakary@yahoo.com

**Comment by bosnjak** [comment]
Hi @phanosh, can you please answer a few questions to help us investigate:
1. Was the user creating a new account using a browser on the PC, navigating to discharge.ch? Or was he using a mobile app for this?
2. Can you get the contents of the email he received? We need the exact link he was sent.
3. Was the user trying to login with the username "Bamba" or "Bamba1"? Because the latter does not exist, only the first one exists.

Also, please make note that the web app is not optimized for mobile use yet, only desktop. However, the functionality shouldn't be impeded, only the UI.

**Comment by phanosh** [comment]
Hellow @bosnj . 
1. The user tried to use the mobile app to ask for his password
2. I requested the user for the link and will send it as soon as I have it.
3. The user was trying to enter with the username Bamba1, which he claims to have created right before he tried. 

As far as I understand, he was eventually able to login with his "old" username (=Bamba) and his account works fine for now.

**Comment by bosnjak** [comment]
@phanosh any update on this? I suppose now that he is logged in, there is no more issues? Should we close this one and re-open in case it happens again?

**Comment by phanosh** [comment]
Hello,
Sorry for bot replying earlier. The issue is closed yes.

**Comment by bosnjak** [comment]
Thanks @phanosh, please close this ticket.
