### ISSUE TITLE
Folder "Pending" on discharge app

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#29]
Dear Beat,

Robert and I asked ourselves, what the folder "Pending" in the menu, right under "Measurements" is for. We thought it would show the measurements, that havn't been uploaded yet or the measurements that havn't been processed yet. But whenever I checked the folder, it was empty. Thank you for clearifying!

Kind regards,

Timo

**Comment by bosnjak** [comment]
Hi @timoherberz, the Pending screen, as is now, shows the measurements that are waiting to be synchronized with the cloud. If you are on the field and don't have the data connection or WiFi, and you click to upload the measurement, it will be listed in the Pending screen until you get access to the internet and the upload can be completely finished. Most of the times the measurement will be sent instantly if you have internet connection, and the measurement will never be Pending, so that's why you don't see it. 

We understand that this screen is not completely intuitive at this point, and not sure if it's even needed in this form, so this might change in the future, as the application development moves forward. We will update you in case of major changes in the future.

Cheers!

**Comment by bosnjak** [comment]
@timoherberz an update about the Pending screen, it will be removed in one of the next versions, and the functionality will be merged into the Measurements screen. It will be simpler and more natural for the user.

Please close this ticket. Thank you!
