### ISSUE TITLE
Different results on discharge app and discharge.ch for discharge, when chosing a certain water level

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#32]
Hello,
again for the site Kikuletwa TPC in Official Sites Pangani:
When chosing the current level [m], the discharge app gives around 60m³/s as discharge for a water level of 1. When checking the rating curve on discharge.ch, the result for one meter water level is 14.2m³/s. Something might be wrong with those calculations.

Thanks in advance!

Kind regards,
Timo

![screenshot 15 02 17](https://cloud.githubusercontent.com/assets/25477472/22980955/106bb2d0-f3ac-11e6-80c2-26d90737a2ec.jpg)
![screenshot_2017-02-15-18-23-15](https://cloud.githubusercontent.com/assets/25477472/22981200/d442d774-f3ac-11e6-9435-ff0d8eeca9b8.png)

**Comment by salpeha** [comment]
Yes, something looks fishy, the point drawn on the graph should be located on top of the line.
In any case, I was taking a look and I don't see on the web a rating curve called  "Official Gauging Curve PWBO". Did someone delete it?

**Comment by timoherberz** [comment]
The rating curve was integrated into a seperate site called 
"RatingCurvePBWO" in the sub-organisation "Kikuletwa@TPC" in the 
organisation "Official Sites Pangani".

Am 20.02.2017 um 13:01 schrieb salpeha:

**Comment by rmunk** [comment]
- The difference in the results of the exponential rating curve comes from discrepancy between web and app formula. It has been fixed with: https://github.com/luethi/discharge/issues/260
- Rating curve drawing issue in the app is resolved with: https://github.com/luethi/discharge/issues/255
- Drawing issue on the web will be handled by: https://github.com/luethi/discharge_web_frontend/issues/383

**Comment by timoherberz** [comment]
Ok, thanks!
