### ISSUE TITLE
waterline setting not possible due to bug

### ISSUE THREAD

**Issue by timoherberz** [luethi/Discharge_Optical_Measurement#34]
Hello,
we are having a bug on two different phones (Samsung J5 & Huawei Y6Pro). When taking a measurement, after selecting the markers, the water line shows as a diagonal on the screen. It is not adjustable and makes the processing of the data impossible. This bug doesn't happen always, maybe in 50% of the cases. It happened on different sites. For us it is a major issue, as we don't know, how the user (gauge reader) will react, when this happens.

Attached you will find a screenshot. I'm sorry, but I can't give you clear indications how to reproduce this error.

Kind regards,
Timo

![screenshot_2017-02-17-14-57-01](https://cloud.githubusercontent.com/assets/25477472/23107316/f7f55496-f70b-11e6-818f-64033a218903.png)

**Comment by salpeha** [comment]
Hi Timo, 

Is this issue only on the phones you listed (Samsung J5 & Huawei Y6Pro)? If you try the same site with another phone does it work? Did you send the debug data so we can take a look? 

In the manual we have a list of the phones where the app has been tested, why are you not using any of those phones?

**Comment by timoherberz** [comment]
Hi,

Yes, it only happened so far on the phones I listed. Yes, if you try the 
site with another phone it works. Even with Samsung J5 & Huawei Y6Pro it 
can work sometimes. While setting the water line, there is no 
possibility of sending debug data or maybe I missed it. Will try to send 
debug data, if/when the error reoccurs.

We want to use phones, which are available locally in Tansania. None of 
the listed phones is available here. That is why we chose to work with 
the Samsung J5.

Kind regards,
Timo

Am 20.02.2017 um 12:42 schrieb salpeha:

**Comment by rmunk** [comment]
Hi Timo,

this is an issue with profile geometry calculation in our discharge processing library that is managed by @TPhilippe. In order to be able to debug the issue we really need you to send us the video and debug data of failed measurement. You can do that from the measurement screen:

![device-2017-01-20-121854](https://cloud.githubusercontent.com/assets/1774159/23548389/95dd6b86-0007-11e7-9c05-571d18eb9682.png)

**Comment by rmunk** [comment]
You can also try bypassing this issue by entering level manually using the pencil icon by the level value. But since level geometry is wrong I am not sure if the processing will work correctly.

**Comment by timoherberz** [comment]
Hi Ranko Munk,
unfortunately I have deleted those videos that produced this error. Will 
upload and let you know, if the error reoccurs!

Am 03.03.2017 um 13:52 schrieb Ranko Munk:

**Comment by TPhilippe** [comment]
@timoherberz @rmunk @luethi  this is clearly a calibration problem and could have different reasons:
- marker world coordinates are wrong
- image coordinates are wrong (actually I can see only two markers in the picture, where are the closer one)
- camera orientation is wrong (it's a hardware App isssue but I don't think that's possible)
- camera calibration failed (that's a library issue).

**Comment by rmunk** [comment]
Since processing library had several updates including the latest major release and problematic movies are lost I think we should close this issue. If the error occurs again please send the debug data as [shown above](https://github.com/luethi/Discharge_Optical_Measurement/issues/34#issuecomment-283924687) and reopen this issue.
